### ISSUE TITLE
Support for react-dnd v16?

### ISSUE THREAD

**Issue by mattcasey** [TechStark/react-dnd-scrolling#15]
React-dnd v16 was released a couple weeks ago with support for React 18 https://github.com/react-dnd/react-dnd/releases/tag/v16.0.0. I've been using it with this library and so far it seems to work OK. However, this package says it is invalid.

One issue I've had, for anyone on Next.js v12: using `next-transpile-modules` was not enough to compile react-dnd and react-dnd-scrolling. I had to either add this to my next.config or stick with react-dnd v15, and I don't know why:
```

module.exports = {
   ...
   experimental: {
      esmExternals: 'loose'
   }
};
```

**Comment by ttt43ttt** [comment]
@mattcasey can you try `react-dnd-scrolling@1.2.4`?

**Comment by mattcasey** [comment]
Works now, thanks @ttt43ttt
