### ISSUE TITLE
StrengthFuncton wrong type for point argument

### ISSUE THREAD

**Issue by KirillZhdanov** [TechStark/react-dnd-scrolling#18]
StrengthFuncton wrong type for point argument, currently it's not number as specified, but {x:number, y:number}. I believe it should be smth like:
```
interface Point {
   x: number;
   y: number:
}
```
And also I guess StrengthFuncton should be StrengthFunction

`export type StrengthFunction = (box: BoxType, point: Point) => number;`

**Comment by ttt43ttt** [comment]
which package is the type being defined?

**Comment by KirillZhdanov** [comment]
Here is the path: https://github.com/TechStark/react-dnd-scrolling/blob/develop/types/index.d.ts
<img width="620" alt="Screen Shot 2022-11-23 at 21 57 30" src="https://user-images.githubusercontent.com/25373900/203617182-5d72f429-06bc-40f0-9fd7-34274fce90dc.png">

**Comment by ttt43ttt** [comment]
@KirillZhdanov would you like to create a PR to fix it?

**Comment by ttt43ttt** [comment]
@KirillZhdanov Updated in https://github.com/TechStark/react-dnd-scrolling/releases/tag/v1.3.0
Thanks for your reporting.
