### ISSUE TITLE
React 17 Support 

### ISSUE THREAD

**Issue by jaymathew** [TechStark/react-dnd-scrolling#2]
When installing this on a project running React 17 I receive the following error.  

`npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from react-dnd-scrolling@1.1.0
npm ERR! node_modules/react-dnd-scrolling`

There are no breaking changes with React 17 so I believe this can be updated fairly easy.

**Comment by JoeDuncko** [comment]
I'm on react 17.0.1, no issues. Maybe you have a conflict in your node modules? I'd delete your package-lock.json and your node-modules folder and `npm install` again.

**Comment by ttt43ttt** [comment]
resolved in `1.2.0`
