### ISSUE TITLE
Module not found: Error: Can't resolve './react-dnd-scrolling'

### ISSUE THREAD

**Issue by CoatiFly** [TechStark/react-dnd-scrolling#21]
rt:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/11940247/208392234-4f4420c6-da46-4bbc-b976-6ff880d97f82.png">

**Comment by ttt43ttt** [comment]
what's the error detail? do you have an example page?

**Comment by CoatiFly** [comment]
@[ttt43ttt](https://github.com/ttt43ttt)![Uploading image.png…]()

**Comment by CoatiFly** [comment]
> what's the error detail? do you have an example page?

ERROR in ./src/components/kanban/kanban.tsx 34:43-75
Module not found: Error: Can't resolve './react-dnd-scrolling' in '/workspaces/gspace/focalboard/webapp/src/components/kanban'
resolve './react-dnd-scrolling' in '/workspaces/gspace/focalboard/webapp/src/components/kanban'
  using description file: /workspaces/gspace/focalboard/webapp/package.json (relative path: ./src/components/kanban)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /workspaces/gspace/focalboard/webapp/package.json (relative path: ./src/components/kanban/react-dnd-scrolling)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling is not a file
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling.tsx doesn't exist
      cjs
        Field 'browser' doesn't contain a valid alias configuration
        /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrollingcjs doesn't exist
      as directory
        existing directory /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling
          using description file: /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/package.json (relative path: .)
            use ./lib/index.js from main in package.json
              using description file: /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/package.json (relative path: ./lib/index.js)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.js doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.js.js doesn't exist
                .jsx
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.js.jsx doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.js.ts doesn't exist
                .tsx
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.js.tsx doesn't exist
                cjs
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.jscjs doesn't exist
                as directory
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/lib/index.js doesn't exist
            using path: /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/index
              using description file: /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/package.json (relative path: ./index)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/index doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/index.js doesn't exist
                .jsx
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/index.jsx doesn't exist
                .ts
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/index.ts doesn't exist
                .tsx
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/index.tsx doesn't exist
                cjs
                  Field 'browser' doesn't contain a valid alias configuration
                  /workspaces/gspace/focalboard/webapp/src/components/kanban/react-dnd-scrolling/indexcjs doesn't exist
 @ ./src/components/centerPanel.tsx 57:33-59
 @ ./src/components/workspace.tsx 43:38-62
 @ ./src/pages/boardPage/boardPage.tsx 35:36-73
 @ ./src/router.tsx 34:36-74
 @ ./src/app.tsx 45:33-52
 @ ./src/main.tsx 12:30-46

**Comment by ttt43ttt** [comment]
`react-dnd-scrolling` should be in the `node_modules` folder. It seems that your tsconfig is not correct.

**Comment by CoatiFly** [comment]
> `react-dnd-scrolling` should be in the `node_modules` folder. It seems that your tsconfig is not correct.

I know，`node_modules` folder have the same mistake。

**Comment by wdh2100** [comment]
same issue

**Comment by pranavmappoli** [comment]
Is this only can Use in React-typescript ?. Is there any way to use in React JS version. Please help

**Comment by ttt43ttt** [comment]
It should work in JS. maybe the recent change breaks it. Could you try an older version `1.2.4` to see if it works?

**Comment by pranavmappoli** [comment]
@ttt43ttt It resolves that issue, but it create a new error like 
"error: 'useDndScrolling' is not exported from 'react-dnd-scrolling')"

**Comment by pranavmappoli** [comment]
Is this possible to fix this issue on the later version ?

**Comment by ttt43ttt** [comment]
@pranavmappoli could you try the latest version?

**Comment by pranavmappoli** [comment]
@ttt43ttt see the below error now

```
Failed to compile.

Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/pppp/Documents/abcdefg-ui/node_modules/react-dnd-scrolling/lib/esm'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
ERROR in ./node_modules/react-dnd-scrolling/lib/esm/index.js 36:0-48
Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/pppp/Documents/abcdefg-ui/node_modules/react-dnd-scrolling/lib/esm'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error
```

**Comment by pranavmappoli** [comment]
@ttt43ttt I understood this issue is with react version 17. But i wont able to upgrade my project due to some dependencies. Is there any other walk around can be done, so this package support to react 17 as well. 

[issue thread](https://github.com/react-dnd/react-dnd/issues/3418#issuecomment-1088008597)

**Comment by ttt43ttt** [comment]
@pranavmappoli can you check what's the exact react version from "node_modules" folder? does the file "jsx-runtime.js" exist in the react folder?

Anyway, it should work if you update to `react-dnd-scrolling@1.3.3`

**Comment by pranavmappoli** [comment]
@ttt43ttt This resolves both issues. But now the scrolling is not working :( . I have tried both hook and " withScrolling".
`React & Dom:17.0.0 `

**Comment by pranavmappoli** [comment]
@ttt43ttt This issue is fixed and can close. Thanks for your support
