### ISSUE TITLE
1.3.4 errors with structuredClone being passed a function

### ISSUE THREAD

**Issue by knownasilya** [TechStark/react-dnd-scrolling#30]
v1.3.3 works fine.

The error is this:

>`Uncaught DOMException: Failed to execute 'structuredClone' on 'Window': function noop() {
} could not be cloned.`

The issue is that the new `defaults` (was updated to v3 from v1) function uses `structuredClone` which can't take functions...

**Comment by ttt43ttt** [comment]
@knownasilya thanks for raising this. This is fixed in version 1.3.6
