### ISSUE TITLE
`withScrolling` function name mismatch

### ISSUE THREAD

**Issue by Waley-Z** [TechStark/react-dnd-scrolling#36]
Hi, I don't understand this part of code. The [`createScrollingComponent`](https://github.com/TechStark/react-dnd-scrolling/blob/c3523f827f49494774060e1239d6485d7e5c24f4/src/index.jsx#L86C1-L86C7) function does not have the same name as [`withScrolling`](https://github.com/TechStark/react-dnd-scrolling/blob/c3523f827f49494774060e1239d6485d7e5c24f4/types/index.d.ts#L34) type declaration. How are they connected? Actually, `withScrolling` has not been referenced anywhere in the code. Should it be renamed to `createScrollingComponent`? Thanks.

**Comment by ttt43ttt** [comment]
@Waley-Z `createScrollingComponent` is `default` exported, so the name doesn't matter technically. But good catch. I've renamed it to `withScrolling` which is used everywhere.
