### ISSUE TITLE
Scrolling up auto scrolls to top 

### ISSUE THREAD

**Issue by Joshandrews43** [TechStark/react-dnd-scrolling#6]
Not sure what's causing this, any ideas? BTW loom cuts out the element when its being dragged, but you can tell it scrolls to top.

https://www.loom.com/share/db39ecc5bf164b98aea4f67b0c2cc94c

**Comment by ttt43ttt** [comment]
Not sure what's the issue. Looks like expected. If you are dragging the element and mouse cursor is at the top of the scroll container, then scroll bar will scroll toward top.

**Comment by yonihorwitz** [comment]
@Joshandrews43 Did you ever resolve this?  Different scenario for me, but my component also scrolls to the top right when I drop at the end of a drag.

Edit: Never mind - it scrolls to top on any state change...
